"""
Gera docs/assets/alerts_data.js com um snapshot real de deteção de anomalia,
reaproveitando os mesmos módulos que main.py usa em produção (download_context,
download_prices, build_all_features, evaluation.anomaly.detect_anomaly), não
uma reimplementação da lógica, pra não repetir o tipo de divergência silenciosa
que já apareceu antes entre o gráfico de acurácia e o header (ver export_data.py).

Diferente dos outros export_*.py, este baixa dados reais (VIX + os 7 ETFs da
carteira) e roda o feature engineering, mas não treina modelo nenhum, rápido
(uns 10-30s), sem cache necessário.

Uso: python docs/export_alerts.py   (rodar a partir da raiz do repositório)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from data.storage import load_portfolio_config
from data.downloader import download_context, download_prices
from features.engineering import build_all_features
from config.settings import MIN_SAMPLES_FEATURES
from evaluation.anomaly import detect_anomaly


def main():
    portfolio_cfg = load_portfolio_config()
    etf_acumul = portfolio_cfg["etf_acumulacao"]

    print("Baixando contexto (VIX, SPY)...")
    context_data, ctx_warnings = download_context()
    if ctx_warnings:
        print("Avisos:", ctx_warnings)

    print(f"Baixando {len(etf_acumul)} ETFs da carteira: {etf_acumul}")
    raw_data = download_prices(etf_acumul)

    print("Calculando features (ATR14, retornos)...")
    featured_data = build_all_features(raw_data, context_data, MIN_SAMPLES_FEATURES)

    anomaly = detect_anomaly(context_data, featured_data, etf_acumul)

    out_path = Path(__file__).resolve().parent / "assets" / "alerts_data.js"
    out_path.write_text(
        "// Generated by docs/export_alerts.py, real snapshot from the same\n"
        "// evaluation.anomaly.detect_anomaly() used in production, not a reimplementation.\n"
        f"const ALERTS_DATA = {json.dumps(anomaly, indent=2, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"OK - {out_path} updated (alerta={anomaly['alerta']})")


if __name__ == "__main__":
    main()
